version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Login to ECR"
      - REPOSITORY_URI=118178009836.dkr.ecr.us-east-1.amazonaws.com/order-service-repo
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 118178009836.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 7)

  build:
    commands:
      - echo "Docker validation"
      - docker version
      - docker info
      - docker run hello-world

      - echo "Build image"
      - docker build -t $REPOSITORY_URI:latest .

      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - printf '[{"name":"order-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json