version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECS_CLUSTER: ecommerce-cluster
    ECS_SERVICE: order-task-service

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Starting Docker daemon..."

      # ✅ Start Docker daemon manually
      - /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &

      # ✅ Wait until Docker is ready
      - timeout 15 sh -c "until docker info; do echo waiting for docker...; sleep 1; done"

  pre_build:
    commands:
      - echo Installing dependencies and building JAR...
      - mvn clean install -DskipTests

      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=118178009836.dkr.ecr.us-east-1.amazonaws.com/order-service-repo
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo Checking Docker...
      - docker version
      - docker info
      - echo Building Docker image...
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"order-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Who am I
      - aws sts get-caller-identity

      - echo Check ECS clusters
      - aws ecs list-clusters --region $AWS_REGION

      - echo Check ECS services
      - aws ecs list-services --cluster $ECS_CLUSTER --region $AWS_REGION

      - echo Restart ECS
      - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment --region $AWS_REGION

artifacts:
  files:
    - imagedefinitions.json
    - target/order-service-1.0.0-SNAPSHOT.jar