spring:
  datasource:
    url: jdbc:postgresql://postgres-order-db.ecommerce.local:5432/order_db_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.ecommerce.order: DEBUG
    org.springframework.web: DEBUG


